name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  # Job 1: Build, Push Docker Image, and Install Ansible
  build-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Log in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build and Push Docker image
      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: yapadinithi/webapp:${{ github.sha }}

      # Step 4: Install Ansible
      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

  # Job 2: Deployment to EC2 Instances
  deploy:
    runs-on: ubuntu-latest
    needs: build-push  # Ensure Job 1 is completed

    steps:
      # Step 5: Deploy to EC2 Instance 1 using Ansible
      - name: Deploy to EC2 Instance 1
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            sudo apt update
            sudo apt install -y ansible
            mkdir -p ~/ansible
            echo "[web]" > ~/ansible/inventory.ini
            echo "${{ secrets.EC2_HOST }}" >> ~/ansible/inventory.ini
            echo "${{ secrets.EC2_HOST_2 }}" >> ~/ansible/inventory.ini
            echo "- name: Example Playbook
              hosts: web
              tasks:
                - name: Ensure Nginx is installed
                  apt:
                    name: nginx
                    state: present" > ~/ansible/playbook.yml
            ansible-playbook -i ~/ansible/inventory.ini ~/ansible/playbook.yml

      # Step 6: Deploy to EC2 Instance 2 using Ansible
      - name: Deploy to EC2 Instance 2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST_2 }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            sudo apt update
            sudo apt install -y ansible
            mkdir -p ~/ansible
            echo "[web]" > ~/ansible/inventory.ini
            echo "${{ secrets.EC2_HOST_2 }}" >> ~/ansible/inventory.ini
            echo "- name: Example Playbook
              hosts: web
              tasks:
                - name: Ensure Nginx is installed
                  apt:
                    name: nginx
                    state: present" > ~/ansible/playbook.yml
            ansible-playbook -i ~/ansible/inventory.ini ~/ansible/playbook.yml
