name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  # Step 1: Build and Push Docker Image
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and Push Docker image to Docker Hub
      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: yapadinithi/webapp:${{ github.sha }}

  # Step 2: Deploy to EC2 Instances
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Deploy to EC2 Instance 1
      - name: Copy files to EC2 Instance 1
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: |
            inventory       # Inventory file
            playbook.yml    # Ansible playbook
            deploy          # Role directory
          target: ~         # Copy files to the home directory

      - name: Run Playbook on EC2 Instance 1
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            sudo apt update
            sudo apt install -y ansible
            ansible-playbook -i ~/inventory ~/playbook.yml

      # Deploy to EC2 Instance 2
      - name: Copy files to EC2 Instance 2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST_2 }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: |
            inventory       # Inventory file
            playbook.yml    # Ansible playbook
            deploy          # Role directory
          target: ~         # Copy files to the home directory

      - name: Run Playbook on EC2 Instance 2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST_2 }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            sudo apt update
            sudo apt install -y ansible
            ansible-playbook -i ~/inventory ~/playbook.yml
