name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  # Job 1: Build and Push Docker Image
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Log in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build and Push Docker image
      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: yapadinithi/webapp:${{ github.sha }}

  # Job 2: Deploy to EC2 Instances
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push  # Ensure Job 1 completes before running this job

    steps:
      # Step 1: Deploy to EC2 Instance 1
      - name: Deploy to EC2 Instance 1
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}  # EC2 instance 1
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            # Install Ansible if not already installed
            sudo apt update
            sudo apt install -y ansible

            # Create the Ansible playbook on the instance
            echo "${{ secrets.ANSIBLE_PLAYBOOK }}" > playbook.yml

            # Run the Ansible playbook
            ansible-playbook -i inventory.ini playbook.yml

      # Step 2: Deploy to EC2 Instance 2
      - name: Deploy to EC2 Instance 2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST_2 }}  # EC2 instance 2
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            # Install Ansible if not already installed
            sudo apt update
            sudo apt install -y ansible

            # Create the Ansible playbook on the instance
            echo "${{ secrets.ANSIBLE_PLAYBOOK }}" > playbook.yml

            # Run the Ansible playbook
            ansible-playbook -i inventory.ini playbook.yml
