name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Log in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build and Push Docker image
      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: yapadinithi/webapp:${{ github.sha }}

      # Step 4: Install Ansible
      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      # Step 5: Deploy to EC2 Instance 1 using Ansible
      - name: Deploy to EC2 Instance 1
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}  # EC2 instance 1
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            # Install Ansible if not already installed
            sudo apt update
            sudo apt install -y ansible

            # Copy the playbook and roles from the repository to the EC2 instance
            mkdir -p ~/ansible/roles/webapp/tasks
            cp -r $GITHUB_WORKSPACE/webapp ~/ansible/roles/webapp
            cp $GITHUB_WORKSPACE/playbook.yml ~/ansible/playbook.yml

            # Run the playbook
            ansible-playbook -i inventory.ini ~/ansible/playbook.yml

      # Step 6: Deploy to EC2 Instance 2 using Ansible
      - name: Deploy to EC2 Instance 2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST_2 }}  # EC2 instance 2
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            # Install Ansible if not already installed
            sudo apt update
            sudo apt install -y ansible

            # Copy the playbook and roles from the repository to the EC2 instance
            mkdir -p ~/ansible/webapp/tasks
            cp -r $GITHUB_WORKSPACE/webapp ~/ansible/roles/webapp
            cp $GITHUB_WORKSPACE/playbook.yml ~/ansible/playbook.yml

            # Run the playbook
            ansible-playbook -i inventory.ini ~/ansible/playbook.yml
